import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Söhne", "ui-sans-serif", "system-ui", "-apple-system", "BlinkMacSystemFont", "Inter", "Segoe UI", "Roboto", "Helvetica Neue", "Arial", "sans-serif"],
        serif: ["ui-serif", "Georgia", "Cambria", "Times New Roman", "Times", "serif"],
        mono: ["Fira Code", "Fira Mono", "ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "Liberation Mono", "Courier New", "monospace"],
        headline: ["Noto Serif", "serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        chart: {
          "1": "var(--chart-1)",
          "2": "var(--chart-2)",
          "3": "var(--chart-3)",
          "4": "var(--chart-4)",
          "5": "var(--chart-5)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar-background)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
        "primary-container": "#002147",
        "surface": "#f8f9fb",
        "tertiary-fixed": "#ffdad9",
        "outline-variant": "#c4c6cf",
        "surface-tint": "#465f88",
        "inverse-surface": "#2d3133",
        "tertiary": "#200003",
        "inverse-on-surface": "#eff1f3",
        "secondary-fixed-dim": "#aad0b1",
        "tertiary-fixed-dim": "#ffb3b3",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#920022",
        "on-secondary-fixed": "#00210e",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#2c4e36",
        "surface-variant": "#e0e3e5",
        "on-primary": "#ffffff",
        "surface-dim": "#d8dadc",
        "primary-fixed": "#d6e3ff",
        "on-secondary-container": "#486a51",
        "surface-container-highest": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#aec7f6",
        "surface-container-high": "#e6e8ea",
        "on-primary-fixed-variant": "#2d476f",
        "surface-container": "#eceef0",
        "on-primary-fixed": "#001b3d",
        "on-surface-variant": "#44474e",
        "tertiary-container": "#4b000d",
        "surface-container-low": "#f2f4f6",
        "on-error-container": "#93000a",
        "surface-bright": "#f8f9fb",
        "secondary-container": "#10b981",
        "inverse-primary": "#aec7f6",
        "on-primary-container": "#ffffff",
        "on-tertiary-fixed": "#40000a",
        "secondary-fixed": "#c5eccc",
        "on-secondary": "#ffffff",
        "on-surface": "#1d2a3d",
        "on-tertiary-container": "#ff3953",
        "brand-green": "#10b981",
        "brand-amber": "#f59e0b",
        "brand-red": "#ef4444"
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
} satisfies Config;
