import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { cn } from "@/lib/utils";

export type TrainingGuideSectionId =
  | "overview"
  | "export-filters"
  | "training-artifacts"
  | "approved-truth"
  | "learning-queue"
  | "edit-truth-row"
  | "bulk-actions";

export type TrainingGuideSection = {
  id: TrainingGuideSectionId;
  label: string;
  title: string;
  summary: string;
  points: string[];
};

export const TRAINING_PAGE_GUIDE_SECTIONS: TrainingGuideSection[] = [
  {
    id: "overview",
    label: "Overview",
    title: "Training page overview",
    summary:
      "Use this page to review truth rows, run bulk updates, prepare frozen datasets, and move a trained style model into production.",
    points: [
      "Recommended model rollout order: 1) confirm approved truth coverage, 2) Build gold dataset, 3) Train style model, 4) Use this model in engine.",
      "Parser hints and style models are different systems. Push hints to parser updates deterministic DOI/journal matching only, while style model training updates ML style routing.",
      "Use Download NDJSON export when you need offline analysis, audits, or external training runs.",
      "Use Add truth row to create a new canonical reviewed citation entry manually.",
      "Use the Page guide button whenever you need explanations for each container and control on this page.",
    ],
  },
  {
    id: "export-filters",
    label: "Export filters",
    title: "Export row purpose",
    summary:
      "This row configures exactly what gets exported. It does not change existing rows by itself.",
    points: [
      "Export task selects which workflow output you want (for example style or authority-pack scoped exports).",
      "Truth scope controls whether export includes core truth or other truth scopes you are explicitly targeting.",
      "Holdout version is optional and should be set only when you want a specific sealed holdout subset.",
      "Dataset version is optional and is mainly used when you want deterministic exports from a known frozen dataset.",
      "Style eval suite narrows style exports to a specific evaluation lane when needed.",
      "Certified rows only should stay enabled for production-safe exports so uncertified rows are excluded.",
      "Exclude quarantined rows should stay enabled for model builds unless you are explicitly auditing quarantined content.",
      "If you are doing normal row review/edit/bulk actions, you can leave this entire row unchanged.",
    ],
  },
  {
    id: "training-artifacts",
    label: "Training artifacts",
    title: "Training artifacts container",
    summary:
      "This container is where admin-reviewed truth becomes a frozen dataset and then a live style model.",
    points: [
      "New model version name is autogenerated. Keep auto when possible; edit manually only if you need a custom release name.",
      "Gold dataset to train from chooses the frozen dataset used for style training. Newest is auto-selected by default.",
      "Push hints to parser publishes DOI/journal/ISSN hint packs from reviewed truth so deterministic parser decisions improve immediately.",
      "Build gold dataset freezes current eligible reviewed rows into a versioned dataset snapshot for reproducible training.",
      "Train style model trains a new bundle from the selected frozen dataset; it does not make the model live yet.",
      "Use this model in engine promotes the newly trained bundle to live traffic.",
      "Safe production flow: freeze dataset, train model, verify expected version, then promote.",
      "If you only need deterministic parser improvements and not ML changes, use Push hints to parser without running model training.",
    ],
  },
  {
    id: "approved-truth",
    label: "Approved truth",
    title: "Approved truth container",
    summary:
      "This is the primary admin workspace for filtering, reviewing, editing, certifying, and bulk-updating truth rows.",
    points: [
      "Top filters narrow rows by trust, split, row status, style, gold kind, evaluation suite, and certification view.",
      "Pagination controls let you move across pages and jump directly to a page number for large datasets.",
      "Select rows with checkboxes, then run bulk actions on selected rows or on configured page ranges.",
      "Edit opens the canonical truth editor for one row, including expected fields and linked style variant review.",
      "Delete removes rows permanently; use only when the row should not remain in approved truth.",
      "Certify marks task-scope certification state, which directly affects export eligibility.",
      "Bulk trust/status updates are useful for governance cleanup across many rows at once.",
      "Row highlights (green/red) and toasts show which rows/pages succeeded or failed after bulk background jobs.",
    ],
  },
  {
    id: "learning-queue",
    label: "Learning queue",
    title: "Learning queue container",
    summary:
      "Learning queue contains incoming candidate rows that are not yet approved truth.",
    points: [
      "Use this list to inspect queued candidates before they become governed approved truth rows.",
      "Show processed switches the queue from pending items to already-handled promoted or processed records.",
      "Use the selection checkboxes when multiple queued references should receive the same decision in one review pass.",
      "Promote opens the promotion dialog where you set reviewed fields and required governance metadata.",
      "Promote selected applies one shared expected type, input style label, and governance decision across the selected queue groups while keeping each row's detected field values.",
      "Mark processed lets you clear selected queue groups without promoting them when they were already handled elsewhere or should be skipped.",
      "Only promote rows that were validated and are suitable for inclusion in approved truth.",
      "Once promoted, the item links to the target approved-truth row and is treated as processed.",
    ],
  },
  {
    id: "edit-truth-row",
    label: "Edit truth row",
    title: "Edit truth row dialog",
    summary:
      "This dialog is the canonical truth editor for one citation row and is the source of record for exports.",
    points: [
      "Raw citation text is the observed input string; keep it faithful to the source citation.",
      "Expected fields are canonical truth fields. Fill what is known; leave irrelevant fields blank.",
      "Expected type sets the citation family (for example journal article, book, report) used for validation and rendering behavior.",
      "Input style label is the observed style of the input citation and is used by current style/core classifier workflows.",
      "Prefill from engine seeds fields from local parser output for faster editing; always review before save.",
      "Crossref fill replaces expected fields with Crossref-backed values (DOI-driven) where available.",
      "Save canonical fields before generating, editing, or approving style variants.",
      "When canonical truth fields change, existing variants can become stale and should be regenerated or explicitly re-approved.",
      "Generate all six variants creates style outputs for review lanes; these are linked variants and not direct core classifier rows.",
    ],
  },
  {
    id: "bulk-actions",
    label: "Bulk actions",
    title: "Bulk actions and background jobs",
    summary:
      "Bulk operations run asynchronously and report progress by page, with result highlights and completion/failure toasts.",
    points: [
      "Use bulk prefill to refresh many rows from the local engine parser path.",
      "Use bulk Crossref to replace expected fields from DOI-backed Crossref metadata where matches exist.",
      "Use bulk certify to apply task-scope certification across selected rows/page ranges.",
      "Use bulk update to change trust level and row status for many rows in one action.",
      "Page-range mode lets you process a bounded window (for example pages 130-250) instead of all filtered pages.",
      "Progress toasts report completed pages so you can track long operations clearly.",
      "If a job fails, the failure toast includes last successful page so you can resume from the next page safely.",
      "Buttons stay disabled during active jobs to prevent overlapping writes and inconsistent state.",
    ],
  },
];

interface AdminTrainingGuideDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  section: TrainingGuideSectionId;
  onSectionChange: (section: TrainingGuideSectionId) => void;
}

export function AdminTrainingGuideDialog({
  open,
  onOpenChange,
  section,
  onSectionChange,
}: AdminTrainingGuideDialogProps) {
  const trainingGuideSectionIndex = Math.max(
    TRAINING_PAGE_GUIDE_SECTIONS.findIndex(
      (guideSection) => guideSection.id === section,
    ),
    0,
  );
  const activeTrainingGuideSection =
    TRAINING_PAGE_GUIDE_SECTIONS[trainingGuideSectionIndex] ??
    TRAINING_PAGE_GUIDE_SECTIONS[0];
  const canMoveToPreviousTrainingGuideSection = trainingGuideSectionIndex > 0;
  const canMoveToNextTrainingGuideSection =
    trainingGuideSectionIndex < TRAINING_PAGE_GUIDE_SECTIONS.length - 1;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[92dvh] w-[98vw] max-w-[1220px] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Training page guide</DialogTitle>
          <DialogDescription className="sr-only">
            Training page guide
          </DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 md:grid-cols-[240px_minmax(0,1fr)]">
          <aside className="rounded-lg border border-slate-200 bg-slate-50 p-2 dark:border-slate-700 dark:bg-slate-900/50">
            <nav className="flex flex-col gap-1" aria-label="Guide sections">
              {TRAINING_PAGE_GUIDE_SECTIONS.map((guideSection, index) => (
                <button
                  key={guideSection.id}
                  type="button"
                  className={cn(
                    "rounded-md px-3 py-2 text-left text-sm transition-colors",
                    guideSection.id === activeTrainingGuideSection.id
                      ? "bg-slate-900 font-semibold text-white dark:bg-slate-100 dark:text-slate-900"
                      : "text-slate-700 hover:bg-slate-100 dark:text-slate-200 dark:hover:bg-slate-800/70",
                  )}
                  onClick={() => onSectionChange(guideSection.id)}
                >
                  {index + 1}. {guideSection.label}
                </button>
              ))}
            </nav>
          </aside>
          <section className="space-y-3 break-words">
            <div>
              <p className="text-xs uppercase tracking-[0.12em] text-slate-500">
                {activeTrainingGuideSection.label}
              </p>
              <h3 className="mt-1 text-lg font-semibold text-slate-900 dark:text-slate-100">
                {activeTrainingGuideSection.title}
              </h3>
              <p className="mt-1 text-sm text-slate-600 dark:text-slate-300">
                {activeTrainingGuideSection.summary}
              </p>
            </div>
            <div className="space-y-2 text-sm text-slate-700 dark:text-slate-200">
              {activeTrainingGuideSection.points.map((point, pointIndex) => (
                <p key={`${activeTrainingGuideSection.id}:${pointIndex}`}>
                  {point}
                </p>
              ))}
            </div>
          </section>
        </div>
        <DialogFooter className="sm:justify-between">
          <div className="flex flex-wrap gap-2">
            <Button
              type="button"
              variant="outline"
              disabled={!canMoveToPreviousTrainingGuideSection}
              onClick={() => {
                if (!canMoveToPreviousTrainingGuideSection) {
                  return;
                }
                const previousSection =
                  TRAINING_PAGE_GUIDE_SECTIONS[
                    trainingGuideSectionIndex - 1
                  ] ?? TRAINING_PAGE_GUIDE_SECTIONS[0];
                onSectionChange(previousSection.id);
              }}
            >
              Previous section
            </Button>
            <Button
              type="button"
              variant="outline"
              disabled={!canMoveToNextTrainingGuideSection}
              onClick={() => {
                if (!canMoveToNextTrainingGuideSection) {
                  return;
                }
                const nextSection =
                  TRAINING_PAGE_GUIDE_SECTIONS[
                    trainingGuideSectionIndex + 1
                  ] ??
                  TRAINING_PAGE_GUIDE_SECTIONS[
                    TRAINING_PAGE_GUIDE_SECTIONS.length - 1
                  ];
                onSectionChange(nextSection.id);
              }}
            >
              Next section
            </Button>
          </div>
          <Button
            type="button"
            variant="outline"
            onClick={() => onOpenChange(false)}
          >
            Close
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
