export const JOURNAL_ABBREVIATIONS: Record<string, string> = {
    // Top STEM / Medical Abbreviations mappings
    "JAMA": "Journal of the American Medical Association",
    "N. Engl. J. Med.": "New England Journal of Medicine",
    "NEJM": "New England Journal of Medicine",
    "BMJ": "British Medical Journal",
    "Lancet": "The Lancet",
    "Nat. Med.": "Nature Medicine",
    "Sci. Transl. Med.": "Science Translational Medicine",
    "Nat. Immunol.": "Nature Immunology",
    "Nat. Genet.": "Nature Genetics",
    "Nat. Biotechnol.": "Nature Biotechnology",
    "Cell": "Cell",
    "Science": "Science",
    "Nat.": "Nature",
    "Nature": "Nature", // Catch all to prevent issues
    "PNAS": "Proceedings of the National Academy of Sciences",
    "Proc. Natl. Acad. Sci. U. S. A.": "Proceedings of the National Academy of Sciences",
    "J. Clin. Oncol.": "Journal of Clinical Oncology",
    "JCO": "Journal of Clinical Oncology",
    "Lancet Oncol.": "The Lancet Oncology",
    "CA Cancer J. Clin.": "CA: A Cancer Journal for Clinicians",
    "J. Am. Coll. Cardiol.": "Journal of the American College of Cardiology",
    "JACC": "Journal of the American College of Cardiology",
    "Circulation": "Circulation",
    "Eur. Heart J.": "European Heart Journal",
    "Gastroenterology": "Gastroenterology",
    "Gut": "Gut",
    "Hepatology": "Hepatology",
    "J. Hepatol.": "Journal of Hepatology",
    "Am. J. Respir. Crit. Care Med.": "American Journal of Respiratory and Critical Care Medicine",
    "Lancet Respir. Med.": "The Lancet Respiratory Medicine",
    "Ann. Intern. Med.": "Annals of Internal Medicine",
    "JAMA Intern. Med.": "JAMA Internal Medicine",
    "Arch. Intern. Med.": "Archives of Internal Medicine",
    "Lancet Neurol.": "The Lancet Neurology",
    "JAMA Neurol.": "JAMA Neurology",
    "Ann. Neurol.": "Annals of Neurology",
    "Neurology": "Neurology",
    "Am. J. Psychiatry": "American Journal of Psychiatry",
    "JAMA Psychiatry": "JAMA Psychiatry",
    "Mol. Psychiatry": "Molecular Psychiatry",
    "Biol. Psychiatry": "Biological Psychiatry",
    "Pediatrics": "Pediatrics",
    "JAMA Pediatr.": "JAMA Pediatrics",
    "Ann. Surg.": "Annals of Surgery",
    "JAMA Surg.": "JAMA Surgery",
    "Blood": "Blood",
    "Leukemia": "Leukemia",
    "Clin. Infect. Dis.": "Clinical Infectious Diseases",
    "J. Infect. Dis.": "Journal of Infectious Diseases",
    "Lancet Infect. Dis.": "The Lancet Infectious Diseases",
    "Diabetes": "Diabetes",
    "Diabetes Care": "Diabetes Care",
    "Endocrinology": "Endocrinology",
    "J. Clin. Endocrinol. Metab.": "Journal of Clinical Endocrinology & Metabolism",
    "Am. J. Kidney Dis.": "American Journal of Kidney Diseases",
    "J. Am. Soc. Nephrol.": "Journal of the American Society of Nephrology",
    "Kidney Int.": "Kidney International",
    "Arthritis Rheumatol.": "Arthritis & Rheumatology",
    "Ann. Rheum. Dis.": "Annals of the Rheumatic Diseases",
    "Allergy": "Allergy",
    "J. Allergy Clin. Immunol.": "Journal of Allergy and Clinical Immunology",
    "Am. J. Obstet. Gynecol.": "American Journal of Obstetrics and Gynecology",
    "Obstet. Gynecol.": "Obstetrics & Gynecology",
    "Radiology": "Radiology",
    "Ophthalmology": "Ophthalmology",
    "Arch. Ophthalmol.": "Archives of Ophthalmology",
    "Am. J. Sports Med.": "American Journal of Sports Medicine",
    "Br. J. Sports Med.": "British Journal of Sports Medicine",
    "Pain": "Pain",
    "Am. J. Public Health": "American Journal of Public Health",
    "Cochrane Database Syst. Rev.": "Cochrane Database of Systematic Reviews",
    "Health Aff.": "Health Affairs",

    // Computer Science & Engineering
    "IEEE Trans. Pattern Anal. Mach. Intell.": "IEEE Transactions on Pattern Analysis and Machine Intelligence",
    "IEEE Trans. Neural Netw. Learn. Syst.": "IEEE Transactions on Neural Networks and Learning Systems",
    "IEEE Trans. Image Process.": "IEEE Transactions on Image Processing",
    "IEEE Trans. Knowl. Data Eng.": "IEEE Transactions on Knowledge and Data Engineering",
    "IEEE Trans. Signal Process.": "IEEE Transactions on Signal Processing",
    "IEEE Trans. Commun.": "IEEE Transactions on Communications",
    "IEEE Trans. Wireless Commun.": "IEEE Transactions on Wireless Communications",
    "IEEE J. Sel. Areas Commun.": "IEEE Journal on Selected Areas in Communications",
    "IEEE Trans. Inf. Theory": "IEEE Transactions on Information Theory",
    "IEEE Trans. Comput.": "IEEE Transactions on Computers",
    "IEEE Trans. Parallel Distrib. Syst.": "IEEE Transactions on Parallel and Distributed Systems",
    "IEEE Trans. Software Eng.": "IEEE Transactions on Software Engineering",
    "IEEE Trans. Autom. Control": "IEEE Transactions on Automatic Control",
    "IEEE Trans. Robot.": "IEEE Transactions on Robotics",
    "IEEE Trans. Cybern.": "IEEE Transactions on Cybernetics",
    "IEEE Trans. Ind. Electron.": "IEEE Transactions on Industrial Electronics",
    "IEEE Trans. Power Syst.": "IEEE Transactions on Power Systems",
    "IEEE Trans. Power Electron.": "IEEE Transactions on Power Electronics",
    "IEEE Trans. Smart Grid": "IEEE Transactions on Smart Grid",
    "IEEE Trans. Veh. Technol.": "IEEE Transactions on Vehicular Technology",
    "IEEE Trans. Med. Imaging": "IEEE Transactions on Medical Imaging",
    "IEEE Trans. Microw. Theory Tech.": "IEEE Transactions on Microwave Theory and Techniques",
    "IEEE Trans. Antennas Propag.": "IEEE Transactions on Antennas and Propagation",
    "IEEE Trans. Electron Devices": "IEEE Transactions on Electron Devices",
    "IEEE Trans. Circuits Syst. I Regul. Pap.": "IEEE Transactions on Circuits and Systems I: Regular Papers",
    "IEEE Trans. Circuits Syst. Video Technol.": "IEEE Transactions on Circuits and Systems for Video Technology",
    "IEEE Trans. Multimedia": "IEEE Transactions on Multimedia",
    "ACM Comput. Surv.": "ACM Computing Surveys",
    "Commun. ACM": "Communications of the ACM",
    "J. ACM": "Journal of the ACM",
    "ACM Trans. Graph.": "ACM Transactions on Graphics",
    "ACM Trans. Database Syst.": "ACM Transactions on Database Systems",
    "ACM Trans. Comput. Syst.": "ACM Transactions on Computer Systems",
    "ACM Trans. Program. Lang. Syst.": "ACM Transactions on Programming Languages and Systems",
    "ACM Trans. Softw. Eng. Methodol.": "ACM Transactions on Software Engineering and Methodology",
    "Artif. Intell.": "Artificial Intelligence",
    "J. Mach. Learn. Res.": "Journal of Machine Learning Research",
    "Mach. Learn.": "Machine Learning",
    "Pattern Recognit.": "Pattern Recognition",
    "Comput. Vis. Image Underst.": "Computer Vision and Image Understanding",
    "Int. J. Comput. Vis.": "International Journal of Computer Vision",
    "Bioinformatics": "Bioinformatics",
    "Briefings Bioinf.": "Briefings in Bioinformatics",
    "Comput. Biol. Med.": "Computers in Biology and Medicine",
    "Neuroimage": "NeuroImage",
    "Med. Image Anal.": "Medical Image Analysis",
    "Inform. Sci.": "Information Sciences",
    "Expert Syst. Appl.": "Expert Systems with Applications",
    "Decis. Support Syst.": "Decision Support Systems",
    "Eur. J. Oper. Res.": "European Journal of Operational Research",
    "Manage. Sci.": "Management Science",
    "Oper. Res.": "Operations Research",
    "Inf. Syst. Res.": "Information Systems Research",
    "MIS Q.": "MIS Quarterly",

    "J Digit Libr": "Journal of Digital Libraries",
    "Int. J. Inf. Manage.": "International Journal of Information Management",
    "Int J Inf Manage": "International Journal of Information Management",
    "J. Inf. Syst.": "Journal of Information Systems",
    "J Inf Syst": "Journal of Information Systems",
    "J. Educ. Technol.": "Journal of Educational Technology",
    "J Educ Technol": "Journal of Educational Technology",
    "Int. J. Web Eng. Technol.": "International Journal of Web Engineering and Technology"
};
