/**
 * shared/schema.ts — Barrel re-export
 *
 * All types, interfaces, validation schemas, and utilities are organised
 * into focused submodules under shared/schema/.  This barrel file
 * preserves backward compatibility so every existing import from
 * '@shared/schema' continues to work with zero consumer changes.
 */

// ── Core domain types ──
export type {
  CitationStyle,
  ReferenceType,
  PatternHit,
  AuthorityData,
  ConfidenceResult,
  AssertionDetail,
  AssertionSummary,
  AssertionHighlight,
  HealthState,
  ReferenceDebugEnvelope,
  Cluster,
  ParsedReference,
  AuthorityStatus,
  TruthMatchType,
  TruthAliasType,
  TruthStalenessReason,
  TruthProvenance,
  ConvertedReference,
  ConversionResponse,
  DuplicateGroup,
  InsertReference,
  Reference,
} from './schema/types';

// ── Failure reporting & admin types ──
export type {
  FailureSource,
  FailureCategory,
  ReportStatus,
  FixType,
  ProposedPattern,
  StageBlameAlternative,
  StageBlameSummary,
  StageLogSummary,
  ReportEngineSnapshot,
  ReferenceReviewPayload,
  ReferenceAdminReviewPayload,
  ReferenceExportPayload,
  ReferenceAnalyticsPayload,
  ReviewEvent,
  ResolutionTrace,
  PatternExportArtifact,
  GeneratedRegressionFixtureMeta,
  TruthAlias,
  ApprovedCanonicalFields,
  FieldApprovalDecision,
  FieldApprovalMap,
  ApprovedTruthEntry,
  CitationReport,
} from './schema/reportTypes';

// ── V2 engine types ──
export type {
  V2SourceType,
  V2FieldSource,
  V2StageId,
  V2StageStatus,
  V2CitationStatus,
  V2StageTiming,
  CanonicalReferenceType,
  FieldValue,
  CanonicalAuthor,
  StageDiagnostic,
  ValidationIssue,
  DuplicateMetadata,
  EnrichmentMetadata,
  ResolutionStatus,
  ResolutionMatchStrategy,
  ResolutionAcceptedCandidate,
  ResolutionQueryEvidence,
  ResolutionMetadata,
  CitationReviewBucket,
  CitationQualityScore,
  SplitMetadata,
  ExtractionMetadata,
  ValidationMetadata,
  InstitutionMappingMetadata,
  InputProfile,
  FieldRepairConfidence,
  AppliedRepairMetadata,
  RepairMissMetadata,
  ResidualArtifactMetadata,
  NormalizationMetadata,
  CitationRenderedOutput,
  V2CitationStageDebug,
  V2CitationDebugTrace,
  V2DebugPayload,
  CanonicalCitation,
  V2DuplicateEntry,
  V2ConversionStats,
  V2Exports,
  V2ProcessingPath,
  V2ConversionResponse,
} from './schema/v2Types';

// ── Validation schemas & runtime utilities ──
export {
  normalizeCitationStyle,
  conversionRequestSchema,
  contactRequestSchema,
  waitlistRequestSchema,
  publicRegistrationRequestSchema,
  publicLoginRequestSchema,
  institutionalRegistrationRequestSchema,
  institutionalLoginRequestSchema,
  userHistoryItemSchema,
  userHistorySnapshotSchema,
  institutionPartnershipRequestSchema,
  adminAccessRequestSchema,
  adminLoginRequestSchema,
  adminApprovalSchema,
  v2ConversionRequestSchema,
  v2ExportFormatSchema,
} from './schema/validation';

export type {
  ContactRequest,
  WaitlistRequest,
  PublicRegistrationRequest,
  PublicLoginRequest,
  InstitutionalRegistrationRequest,
  InstitutionalLoginRequest,
  UserHistoryItem,
  UserHistorySnapshot,
  InstitutionPartnershipRequest,
  AdminAccessRequest,
  AdminLoginRequest,
  AdminApprovalRequest,
  V2ConversionRequest,
  V2ExportFormat,
} from './schema/validation';
