import os
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForTokenClassification
)

def build_label_maps(dataset):
    all_tags = set()
    for seq in dataset["train"]:
        for tag in seq["ner_tags"]:
            all_tags.add(tag)
            
    tags = sorted(list(all_tags))
    if 'O' in tags:
        tags.remove('O')
        tags = ['O'] + tags # Ensure O is index 0
        
    id2label = {i: label for i, label in enumerate(tags)}
    label2id = {label: i for i, label in enumerate(tags)}
    return tags, id2label, label2id

def main():
    # Load dataset generated by Node.js generator
    # Format: {"tokens": ["A", "B"], "ner_tags": ["B-author", "O"]}
    data_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'tmp', 'training_data.jsonl'))
    print(f"Loading dataset from {data_path}")
    
    dataset = load_dataset("json", data_files={"train": data_path})
    
    tags, id2label, label2id = build_label_maps(dataset)
    print(f"Detected labels: {id2label}")
    
    # We use a SciBERT base for sequence labeling
    model_name = "allenai/scibert_scivocab_uncased"
    # Wait, the Tech spec says SIRIS-Lab/citation-parser-ENTITY. 
    # We can either fine-tune it further, or start from base SciBERT. We'll fine-tune the pre-existing NER model!
    model_name = "SIRIS-Lab/citation-parser-ENTITY"
    
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForTokenClassification.from_pretrained(
        model_name,
        num_labels=len(tags),
        id2label=id2label,
        label2id=label2id,
        ignore_mismatched_sizes=True # Since we are dynamically allocating the classification head
    )
    
    def tokenize_and_align_labels(examples):
        tokenized_inputs = tokenizer(examples["tokens"], truncation=True, is_split_into_words=True)
        
        labels = []
        for i, label in enumerate(examples["ner_tags"]):
            word_ids = tokenized_inputs.word_ids(batch_index=i)
            previous_word_idx = None
            label_ids = []
            for word_idx in word_ids:
                if word_idx is None:
                    label_ids.append(-100)
                elif word_idx != previous_word_idx:
                    label_ids.append(label2id[label[word_idx]])
                else:
                    label_ids.append(-100)
                previous_word_idx = word_idx
            labels.append(label_ids)
            
        tokenized_inputs["labels"] = labels
        return tokenized_inputs

    tokenized_datasets = dataset.map(tokenize_and_align_labels, batched=True)
    
    # Split into train/validation (90/10)
    split = tokenized_datasets["train"].train_test_split(test_size=0.1)
    train_dataset = split["train"]
    eval_dataset = split["test"]

    data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer)

    training_args = TrainingArguments(
        output_dir="./citation-ner-model",
        evaluation_strategy="epoch",
        learning_rate=2e-5,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        num_train_epochs=5,
        weight_decay=0.01,
        save_total_limit=2,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        tokenizer=tokenizer,
        data_collator=data_collator,
    )

    trainer.train()
    
    trainer.save_model("./citation-ner-model-final")
    print("Fine-tuning completed. Model saved to ./citation-ner-model-final")

if __name__ == "__main__":
    main()
